apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-image-volume
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: shell
        command: ["sleep", "infinity"]
        image: ghcr.io/cybozu/ubuntu:24.04
        volumeMounts:
        - name: volume
          mountPath: /volume
      volumes:
      - name: volume
        image:
          reference: ghcr.io/cybozu/ubuntu:22.04
          pullPolicy: IfNotPresent
