apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-image-volume
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: shell
        command: ["sleep", "infinity"]
        image: ghcr.io/cybozu/ubuntu:22.04
        volumeMounts:
        - name: volume
          mountPath: /volume
      volumes:
      - name: volume
        image:
          reference: busybox:1.37.0
          pullPolicy: IfNotPresent
